---
################################################################## ADMINISTRADOR KUBERNETES
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: my-pvclass 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv"
---
################################################################## USUARIO KUBERNETES QUE VA A MONTAR SU APP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  storageClassName: my-pvclass 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: myvolumes-container

    command: ['sh', '-c', 'echo Running ; sleep 3600']

    volumeMounts:
      - mountPath: "/my-pv"
        name: my-pv

  volumes:
    - name: my-pv
      persistentVolumeClaim:
       claimName: my-pvc
